import { Student, NavItemType, Product } from './types';

export const INITIAL_STUDENTS: Student[] = [
  {
    nre: '123456',
    expediente: 'E001',
    apellido1: 'García',
    apellido2: 'López',
    nombre: 'Ana',
    grupo: '2ºDAW',
    subgrupo: 'A',
    fechaNacimiento: '2003-05-15',
    telefono: '600111222',
    telefono2: '',
    emailPersonal: 'ana.garcia@email.com',
    emailOficial: 'ana.garcia@edu.es',
    photoUrl: `https://i.pravatar.cc/150?u=ana.garcia`,
    entrevistas: [
        { id: 'ent1', date: '2024-03-15', attendees: 'Tutor, Ana García', notes: 'Revisión del progreso del primer trimestre. Muestra gran interés en desarrollo backend.' },
        { id: 'ent2', date: '2024-05-20', attendees: 'Tutor', notes: 'Seguimiento sobre el proyecto final. Necesita organizar mejor sus tiempos.' }
    ],
    anotaciones: [
        { id: 'ann1', date: '2024-04-10', note: 'Excelente participación en el debate sobre arquitecturas limpias.', type: 'positive' },
        { id: 'ann2', date: '2024-05-22', note: 'Llegó tarde a la presentación del proyecto.', type: 'negative' },
        { id: 'ann3', date: '2024-06-01', note: 'Ha solicitado material extra sobre Docker.', type: 'neutral' },
    ]
  },
  {
    nre: '789012',
    expediente: 'E002',
    apellido1: 'Martínez',
    apellido2: 'Ruiz',
    nombre: 'Carlos',
    grupo: '2ºDAW',
    subgrupo: 'B',
    fechaNacimiento: '2003-08-22',
    telefono: '600333444',
    telefono2: '600555666',
    emailPersonal: 'carlos.martinez@email.com',
    emailOficial: 'carlos.martinez@edu.es',
    photoUrl: `https://i.pravatar.cc/150?u=carlos.martinez`,
    anotaciones: [
         { id: 'ann4', date: '2024-05-15', note: 'Presenta dificultades con las consultas SQL complejas.', type: 'negative' },
    ]
  },
  {
    nre: '345678',
    expediente: 'E003',
    apellido1: 'Sánchez',
    apellido2: 'Gómez',
    nombre: 'Laura',
    grupo: '1ºSMR',
    subgrupo: 'A',
    fechaNacimiento: '2004-01-10',
    telefono: '600777888',
    telefono2: '',
    emailPersonal: 'laura.sanchez@email.com',
    emailOficial: 'laura.sanchez@edu.es',
    photoUrl: `https://i.pravatar.cc/150?u=laura.sanchez`,
    anotaciones: [
       { id: 'ann5', date: '2024-06-05', note: 'Muy proactiva ayudando a sus compañeros con la configuración de la red.', type: 'positive' },
    ]
  },
];

export const NAV_ITEMS: NavItemType[] = [
  'Dashboard',
  'Alumnos',
  'Gestión Práctica',
  'Gestión de Notas',
  'Registro de Salidas',
  'Exámenes Prácticos',
  'Gestión Académica',
  'Cocina',
  'Gestión de la App',
];

export const COURSE_MODULES = [
    { key: 'ofertas_gastronomicas', name: 'Ofertas gastronómicas', trimesters: 2 },
    { key: 'productos_culinarios', name: 'Productos culinarios', trimesters: 2 },
    { key: 'postres_restauracion', name: 'Postres en restauración', trimesters: 2 },
    { key: 'empleabilidad_2', name: 'Itinerario personal para la Empleabilidad II', trimesters: 2 },
    { key: 'proyecto_intermodular', name: 'Proyecto Intermodular', trimesters: 3 },
    { key: 'sostenibilidad', name: 'Sostenibilidad aplicada al sistema productivo', trimesters: 2 },
    { key: 'optativa', name: 'Optativa', trimesters: 2 },
];

export const GROUP_EVALUATION_ITEMS = [
  { id: 'g1', text: 'Planifica y organiza correctamente la mise en place, asegurando que todos los ingredientes, utensilios y herramientas estén listos antes de comenzar.', points: 1.0 },
  { id: 'g2', text: 'Selecciona, manipula y conserva los ingredientes de forma adecuada, garantizando su frescura, calidad y correcta utilización durante todo el proceso de elaboración.', points: 1.5 },
  { id: 'g3', text: 'Controla y ajusta los tiempos de cocción para asegurar que todos los elementos del plato estén en su punto exacto al momento del servicio.', points: 1.0 },
  { id: 'g4', text: 'Mantiene en todo momento las normas de higiene y seguridad alimentaria, asegurando un entorno de trabajo limpio y una correcta manipulación de los alimentos.', points: 1.5 },
  { id: 'g5', text: 'Coordina de forma eficiente el trabajo con tus compañeros, asegurando que la preparación de los platos se realice de manera sincronizada y a tiempo.', points: 1.0 },
  { id: 'g6', text: 'Identifica los errores cometidos durante el proceso de elaboración y plantea posibles soluciones para mejorar en futuras ocasiones.', points: 1.0 },
  { id: 'g7', text: '¿Ha sido capaz de trabajar en equipo y con actitud activa participativa?', points: 1.0 },
  { id: 'g8', text: 'Gestiona los ingredientes sobrantes de forma adecuada, minimizando el desperdicio y aprovechando los productos de manera eficiente.', points: 2.0 },
];

export const INDIVIDUAL_EVALUATION_ITEMS = [
  { id: 'i1', text: '¿Ha realizado operaciones de puesta en marcha de maquinaria y equipos siguiendo los procedimientos establecidos por el profesor?', points: 0.5 },
  { id: 'i2', text: '¿Ha realizado las operaciones de mise-enplace utilizando correctamente útiles y/o herramientas, siguiendo los procedimientos establecidos por el profesor?', points: 1.0 },
  { id: 'i3', text: '¿Ha sido capaz de Interpretar las fichas técnicas o documentación necesaria para las elaboraciones que le han tocado desarrollar?', points: 1.5 },
  { id: 'i4', text: '¿Ha asistido con el material requerido (fichas técnicas, herramientas y utensilios propios) para el desarrollo de sus prácticas diarias?', points: 1.0 },
  { id: 'i5', text: '¿Ha sido capaz de ejecutar las tareas siguiendo los procedimientos establecidos por el profesor, aplicando las técnicas idóneas en función de las prácticas a realizar?', points: 1.0 },
  { id: 'i6', text: '¿Ha sido capaz de trabajar de forma limpia y ordenada durante el desarrollo de las prácticas en el taller aplicando los procedimientos establecidos?', points: 1.0 },
  { id: 'i7', text: '¿Ha sido capaz de trabajar en equipo y con actitud activa participativa?', points: 1.5 },
  { id: 'i8', text: '¿Ha sido capaz de aplicar las técnicas idóneas de conservación de los productos trabajados en el taller hasta el momento de su utilización?', points: 0.5 },
  { id: 'i9', text: '¿Ha sido capaz de realizar las operaciones de mantenimiento y limpieza de la maquinaria y equipos utilizados, cumplimentando los registros asociados?', points: 1.0 },
  { id: 'i10', text: '¿El alumno cuida su higiene personal y asiste con el uniforme completo, limpio y planchado?', points: 1.0 },
];

export const SCORE_LEVELS = [
    { label: 'Excelente', value: 10, color: 'bg-green-500', textColor: 'text-white' },
    { label: 'Notable', value: 8, color: 'bg-blue-500', textColor: 'text-white' },
    { label: 'Aprobado', value: 5, color: 'bg-yellow-500', textColor: 'text-white' },
    { label: 'Insuficiente', value: 2, color: 'bg-red-500', textColor: 'text-white' }
];

export const PRACTICAL_EXAM_RUBRIC_T1 = [
    { 
        id: 'ra1', 
        title: 'R.A.1 – Organización de procesos', 
        weight: 0.20,
        criteria: [
            { id: 'ra1c1', text: 'Planificación y mise en place', levels: { 10: 'Plan completo, fases claras y ordenadas. Anticipa necesidades.', 8: 'Plan adecuado, con leves desajustes de orden o detalle.', 5: 'Plan incompleto, se olvida de fases relevantes.', 2: 'No presenta plan o es caótico.' } },
            { id: 'ra1c2', text: 'Orden, limpieza y conservación', levels: { 10: 'Área impecable, materiales bien gestionados, propone conservación adecuada.', 8: 'Área generalmente ordenada, pequeñas faltas de higiene o conservación.', 5: 'Área desordenada, higiene básica pero descuida conservación.', 2: 'Desorden evidente, faltan medidas de higiene y conservación.' } }
        ]
    },
    { 
        id: 'ra2', 
        title: 'R.A.2 – Técnicas culinarias tradicionales y avanzadas', 
        weight: 0.30,
        criteria: [
            { id: 'ra2c1', text: 'Aplicación de técnicas básicas', levels: { 10: 'Ejecución precisa y profesional (ej. cortes uniformes, cocciones exactas).', 8: 'Ejecución correcta con leves fallos.', 5: 'Técnica básica reconocible pero con fallos de ejecución.', 2: 'Técnica incorrecta o inacabada.' } },
            { id: 'ra2c2', text: 'Aplicación de técnicas avanzadas', levels: { 10: 'Demuestra dominio y adapta técnica al producto (ej. vacío, emulsiones).', 8: 'Correcta aplicación con leves fallos.', 5: 'Aplica técnica avanzada con dificultad, resultado justo.', 2: 'No demuestra conocimiento ni resultado adecuado.' } },
            { id: 'ra2c3', text: 'Evaluación del resultado final', levels: { 10: 'Producto final excelente en textura, sabor, presentación.', 8: 'Buen resultado con leves mejoras posibles.', 5: 'Resultado aceptable pero poco cuidado.', 2: 'Producto mal ejecutado, incomible o inseguro.' } }
        ]
    },
    { 
        id: 'ra3', 
        title: 'R.A.3 – Elaboración a partir de materias primas', 
        weight: 0.30,
        criteria: [
            { id: 'ra3c1', text: 'Creatividad y propuestas', levels: { 10: 'Propone varias elaboraciones bien razonadas, combinaciones equilibradas.', 8: 'Propone elaboraciones correctas pero poco variadas.', 5: 'Propone solo una elaboración básica o repetitiva.', 2: 'No propone elaboraciones coherentes.' } },
            { id: 'ra3c2', text: 'Aprovechamiento de recursos', levels: { 10: 'Máximo aprovechamiento (fondos, recortes, técnicas de reutilización).', 8: 'Aprovecha parte de los recursos, pocos desperdicios.', 5: 'Algún aprovechamiento pero genera desperdicios.', 2: 'Desaprovecha gran parte de las materias primas.' } },
            { id: 'ra3c3', text: 'Organización y ejecución', levels: { 10: 'Trabajo fluido, tiempos bien gestionados, secuencia clara.', 8: 'Trabajo organizado con leves retrasos.', 5: 'Organización justa, se retrasa en fases importantes.', 2: 'Falta de organización, pierde mucho tiempo.' } }
        ]
    },
    { 
        id: 'ra4', 
        title: 'R.A.4 – Necesidades alimenticias específicas', 
        weight: 0.20,
        criteria: [
            { id: 'ra4c1', text: 'Identificación y selección de alimentos', levels: { 10: 'Identifica perfectamente los alimentos excluidos y selecciona sustitutos adecuados.', 8: 'Identifica la mayoría de los alimentos y propone sustitutos aceptables.', 5: 'Identificación incompleta, sustitutos poco adecuados.', 2: 'No identifica exclusiones, usa alimentos prohibidos.' } },
            { id: 'ra4c2', text: 'Prevención de contaminación cruzada', levels: { 10: 'Cumple rigurosamente las normas (utensilios, tablas, almacenaje).', 8: 'Cumple normas con alguna falta menor.', 5: 'Cumple parcialmente, riesgo bajo de contaminación.', 2: 'No respeta normas, riesgo alto de contaminación.' } },
            { id: 'ra4c3', text: 'Resultado final y justificación', levels: { 10: 'Elabora plato adaptado, bien presentado y justifica la importancia de la dieta.', 8: 'Elabora plato correcto, justificación básica.', 5: 'Plato aceptable pero sin coherencia total.', 2: 'Plato incorrecto o no apto para la dieta.' } }
        ]
    },
];

export const PRACTICAL_EXAM_RUBRIC_T2 = [
    { 
        id: 'ra1', 
        title: 'R.A.1 – Organización', 
        weight: 0.20,
        criteria: [
            { id: 'ra1c1', text: 'Planificación y mise en place', levels: { 10: 'Plan detallado y ajustado al tiempo.', 8: 'Correcto con leves ajustes.', 5: 'Incompleto o desordenado.', 2: 'Sin planificación.' } },
            { id: 'ra1c2', text: 'Preparación de materias primas y utensilios', levels: { 10: 'Identifica y prepara todo correctamente.', 8: 'Pequeñas faltas en la preparación.', 5: 'Olvida elementos.', 2: 'No prepara adecuadamente.' } },
            { id: 'ra1c3', text: 'Orden, limpieza y seguridad', levels: { 10: 'Área impecable, normas seguidas.', 8: 'Generalmente ordenado, leves fallos.', 5: 'Desorden notable pero seguro.', 2: 'Caótico, incumple normas.' } },
            { id: 'ra1c4', text: 'Conservación intermedia', levels: { 10: 'Aplica técnicas correctas (abatidor, refrigeración).', 8: 'Conserva bien con alguna falta menor.', 5: 'Básico, descuidos.', 2: 'No aplica medidas adecuadas.' } }
        ]
    },
    { 
        id: 'ra2', 
        title: 'R.A.2 – Técnicas', 
        weight: 0.30,
        criteria: [
            { id: 'ra2c1', text: 'Métodos de cocción', levels: { 10: 'Domina ≥3 métodos, dos en mismo género.', 8: 'Aplica correctamente 3 métodos.', 5: 'Aplica 2 métodos con fallos.', 2: 'No cumple requisito.' } },
            { id: 'ra2c2', text: 'Salsa', levels: { 10: 'Equilibrada, técnica impecable.', 8: 'Correcta, leves fallos.', 5: 'Básica o poco ligada.', 2: 'No elabora o incorrecta.' } },
            { id: 'ra2c3', text: 'Guarniciones', levels: { 10: 'Dos variadas y coherentes.', 8: 'Dos correctas.', 5: 'Una adecuada.', 2: 'No cumple.' } },
            { id: 'ra2c4', text: 'Técnicas de corte y preparación', levels: { 10: 'Precisión profesional.', 8: 'Correcto con leves errores.', 5: 'Poco uniforme.', 2: 'Incorrecto o inseguro.' } },
            { id: 'ra2c5', text: 'Resultado final', levels: { 10: 'Textura, sabor y presentación excelentes.', 8: 'Buen resultado, leves mejoras.', 5: 'Aceptable, mejorable.', 2: 'Mal ejecutado o inseguro.' } }
        ]
    },
    { 
        id: 'ra3', 
        title: 'R.A.3 – Elaboración a partir de materias primas', 
        weight: 0.30,
        criteria: [
            { id: 'ra3c1', text: 'Aperitivo libre', levels: { 10: 'Creativo, equilibrado y bien ejecutado.', 8: 'Correcto, con detalles mejorables.', 5: 'Aceptable pero simple.', 2: 'Incorrecto o incompleto.' } },
            { id: 'ra3c2', text: 'Diseño del plato principal', levels: { 10: 'Equilibrado y armónico.', 8: 'Correcto, leves fallos.', 5: 'Básico, incoherente.', 2: 'Mal planteado.' } },
            { id: 'ra3c3', text: 'Aprovechamiento de recursos', levels: { 10: 'Máximo aprovechamiento de subproductos.', 8: 'Buen aprovechamiento.', 5: 'Algún aprovechamiento básico.', 2: 'Desaprovecha género.' } },
            { id: 'ra3c4', text: 'Gestión del tiempo (2h)', levels: { 10: 'Organiza y termina a tiempo.', 8: 'Ligeros retrasos pero entrega.', 5: 'Retrasos importantes.', 2: 'No termina.' } }
        ]
    },
    { 
        id: 'ra4', 
        title: 'R.A.4 – Necesidades alimenticias específicas', 
        weight: 0.20,
        criteria: [
            { id: 'ra4c1', text: 'Identificación de exclusiones', levels: { 10: 'Reconoce todas las exclusiones.', 8: 'Reconoce la mayoría.', 5: 'Parcial.', 2: 'No identifica.' } },
            { id: 'ra4c2', text: 'Sustituciones adecuadas', levels: { 10: 'Correctos y coherentes.', 8: 'Aceptables.', 5: 'Poco adecuados.', 2: 'Incorrectos.' } },
            { id: 'ra4c3', text: 'Prevención contaminación cruzada', levels: { 10: 'Normas cumplidas rigurosamente.', 8: 'Cumple con leves fallos.', 5: 'Parcialmente correcto.', 2: 'No cumple normas.' } },
            { id: 'ra4c4', text: 'Plato adaptado', levels: { 10: 'Adaptado y justificado.', 8: 'Correcto, justificación básica.', 5: 'Aceptable pero incoherente.', 2: 'Incorrecto o no apto.' } }
        ]
    },
];

export const ACADEMIC_EVALUATION_STRUCTURE = {
  trimestres: [
    {
      name: "1º Trimestre",
      instruments: [
        { name: "Examen 1", type: "manual", key: "examen1", weight: 0.10 },
        { name: "Examen 2", type: "manual", key: "examen2", weight: 0.10 },
        { name: "Servicios 1", type: "calculated", key: "servicios1", weight: 0.15 },
        { name: "Ex. Practico 1", type: "calculated", key: "exPractico1", weight: 0.15 },
      ]
    },
    {
      name: "2º Trimestre",
      instruments: [
        { name: "Examen 3", type: "manual", key: "examen3", weight: 0.10 },
        { name: "Examen 4", type: "manual", key: "examen4", weight: 0.10 },
        { name: "Servicios 2", type: "calculated", key: "servicios2", weight: 0.15 },
        { name: "Ex. Practico 2", type: "calculated", key: "exPractico2", weight: 0.15 },
      ]
    }
  ],
  recuperacion: {
    name: "Recuperación",
    instruments: [
      { name: "Ex. Teorico REC", type: "manual", key: "recuperacion", weight: 0.50 },
      { name: "Ex. Practico REC", type: "calculated", key: "exPracticoRec", weight: 0.50 },
    ]
  }
};

export const PRODUCT_CATEGORIES = ['Carnes', 'Pescados', 'Mariscos', 'Lácteos', 'Verduras', 'Frutas', 'Congelados', 'Almacén', 'Aceites y Vinagres', 'Condimentos', 'Cereales', 'Bebidas', 'Otros'];
export const PRODUCT_UNITS = ['kg', 'litro', 'unidad', 'gramo', 'mililitro', 'manojo'];
export const ALLERGENS = ['Gluten', 'Lactosa', 'Frutos Secos', 'Pescado', 'Huevo', 'Soja', 'Marisco', 'Apio', 'Mostaza', 'Sésamo', 'Sulfitos', 'Altramuces', 'Moluscos', 'Cacahuete'];
export const RECIPE_CATEGORIES = ['Entrantes', 'Sopas y Cremas', 'Ensaladas', 'Arroces y Pastas', 'Carnes', 'Pescados', 'Guarniciones', 'Postres', 'Salsas', 'Bebidas'];

export const ALLERGEN_MAP: { [key: string]: string } = {
  HUE: 'Huevo',
  GLU: 'Gluten',
  PES: 'Pescado',
  CRU: 'Marisco',
  MOL: 'Moluscos',
  API: 'Apio',
  SOY: 'Soja',
  FRA: 'Frutos Secos',
  CAC: 'Cacahuete',
  SES: 'Sésamo',
  MUS: 'Mostaza',
  SUL: 'Sulfitos',
  LAC: 'Lactosa',
};

export const normalizeCategory = (cat: string): string => {
    const mapping: { [key: string]: string } = {
        carnes: 'Carnes',
        pescados: 'Pescados',
        mariscos: 'Mariscos',
        lacteos: 'Lácteos',
        verduras: 'Verduras',
        frutas: 'Frutas',
        congelados: 'Congelados',
        almacen: 'Almacén',
        aceites: 'Aceites y Vinagres',
        condimentos: 'Condimentos',
    };
    return mapping[cat.toLowerCase()] || 'Otros';
};


// FIX: Export RAW_PRODUCTS so it can be used in other files.
export const RAW_PRODUCTS: Array<Omit<Product, 'price'> & {allergens: string[]}> = [
  {"id":"prod_0001","name":"Solomillo de ternera","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0002","name":"Entrecot de buey","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0003","name":"Filete de ternera","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0004","name":"Carne picada de ternera 80/20","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0005","name":"Lomo bajo de cerdo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0006","name":"Secreto ibérico","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0007","name":"Presa ibérica","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0008","name":"Costillas de cerdo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0009","name":"Panceta fresca","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0010","name":"Pechuga de pollo entera sin piel","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0011","name":"Muslo de pollo deshuesado","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0012","name":"Alitas de pollo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0013","name":"Hígado de pollo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0014","name":"Pato entero","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0015","name":"Foie fresco","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0016","name":"Chuleta de cordero","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0017","name":"Pierna de cordero deshuesada","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0018","name":"Carrilleras de ternera","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0019","name":"Rabo de ternera","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0020","name":"Conejo entero","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0021","name":"Lomo de cerdo adobado","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0022","name":"Tocino ahumado","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0023","name":"Pavo entero","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0024","name":"Magret de pato","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0025","name":"Lengua de ternera","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0026","name":"Morcillo de ternera","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0027","name":"Pies de cerdo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0028","name":"Chorizo fresco para cocinar","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0029","name":"Morcilla fresca","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0030","name":"Albóndigas de ternera sin huevo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0031","name":"Ternera para guisar en trozos","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0032","name":"Cerdo para estofado","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0033","name":"Pechuga de pavo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0034","name":"Codornices enteras","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0035","name":"Palomas","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0036","name":"Liebre","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0037","name":"Ciervo en trozos","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0038","name":"Jabalí para estofado","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0039","name":"Pato confitado","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0040","name":"Hamburguesas de ternera 100%","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0041","name":"Costillar de cerdo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0042","name":"Panceta ahumada en láminas","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0043","name":"Lomo de cerdo en filetes","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0044","name":"Pechuga de pollo en filetes","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0045","name":"Alitas de pollo marinadas","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0046","name":"Muslos de pollo enteros","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0047","name":"Pavo picado","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0048","name":"Ternera picada magra 90/10","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0049","name":"Cerdo picado","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0050","name":"Mezcla de carne picada (ternera + cerdo)","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0051","name":"Churrasco de ternera","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0052","name":"Falda de ternera","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0053","name":"Aleta de ternera","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0054","name":"Riñones de ternera","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0055","name":"Mollejas de pollo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0056","name":"Pata de pollo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0057","name":"Cuello de cordero","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0058","name":"Paletilla de cordero","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0059","name":"Costeletas de cordero","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0060","name":"Hígado de cordero","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0061","name":"Conejo troceado","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0062","name":"Liebre troceada","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0063","name":"Pato en cuartos","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0064","name":"Pechuga de pato","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0065","name":"Alitas de pato","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0066","name":"Ternera Angus entera (referencia)","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0067","name":"Wagyu A5 en filetes","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0068","name":"Cerdo ibérico de bellota entero (referencia)","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0069","name":"Presa ibérica envasada al vacío","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0070","name":"Secreto ibérico envasado al vacío","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0071","name":"Pluma ibérica","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0072","name":"Panceta ibérica","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0073","name":"Tocino ibérico","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0074","name":"Chuleta de buey","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0075","name":"Filete de buey","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0076","name":"Solomillo de buey","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0077","name":"Ternera lechal entera (referencia)","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0078","name":"Cordero lechal entero","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0079","name":"Pechuga de pollo campero","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0080","name":"Huevo de codorniz (unidad)","category":"carnes","unit":"unidad","allergens":["HUE"]},
  {"id":"prod_0081","name":"Hígado de pato (foie base)","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0082","name":"Pato estofado en conserva","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0083","name":"Conejo en salsa","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0084","name":"Albóndigas caseras con huevo","category":"carnes","unit":"kg","allergens":["HUE"]},
  {"id":"prod_0085","name":"Carne de caza surtida","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0086","name":"Pavo relleno (base sin relleno)","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0087","name":"Pechuga de pavo marinada","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0088","name":"Lomo de cerdo marinado","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0089","name":"Costillas de cerdo al estilo BBQ","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0090","name":"Ternera wok en tiras","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0091","name":"Cerdo wok en tiras","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0092","name":"Pollo wok en dados","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0093","name":"Pato wok en dados","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0094","name":"Chuleta de cerdo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0095","name":"Filete de cerdo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0096","name":"Presa de cerdo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0097","name":"Solomillo de cerdo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0098","name":"Ternera para kebab","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0099","name":"Cerdo para kebab","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0100","name":"Pollo para asar entero","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0101","name":"Pollo campero entero","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0102","name":"Pavo campero entero","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0103","name":"Gallina para caldo","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0104","name":"Capón entero","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0105","name":"Pato fresco entero sin eviscerar","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0106","name":"Codorniz limpia","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0107","name":"Perdiz limpia","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0108","name":"Faisán entero","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0109","name":"Paloma limpia","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0110","name":"Conejo limpio sin piel","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0111","name":"Liebre limpia","category":"carnes","unit":"unidad","allergens":[]},
  {"id":"prod_0112","name":"Ciervo entero (referencia)","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0113","name":"Jabalí entero (referencia)","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0114","name":"Corazón de ternera","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0115","name":"Hígado de ternera","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0116","name":"Riñones de cerdo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0117","name":"Mollejas de ternera","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0118","name":"Callos de ternera limpios","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0119","name":"Lengua de cerdo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0120","name":"Oreja de cerdo limpia","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0121","name":"Morro de cerdo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0122","name":"Panza de cerdo (trotters)","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0123","name":"Sesos de ternera","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0124","name":"Sesos de cerdo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0125","name":"Testículos de ternera (huevas)","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0126","name":"Timos de ternera","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0127","name":"Huesos de ternera para caldo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0128","name":"Huesos de pollo para caldo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0129","name":"Alitas de pollo para caldo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0130","name":"Pechuga de pollo con hueso","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0131","name":"Muslo de pollo con hueso","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0132","name":"Pavo picado con pavo y cerdo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0133","name":"Carne de cordero picada","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0134","name":"Albóndigas de cordero con huevo","category":"carnes","unit":"kg","allergens":["HUE"]},
  {"id":"prod_0135","name":"Chorizo fresco sin pimentón","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0136","name":"Morcilla de cebolla","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0137","name":"Morcilla de arroz","category":"carnes","unit":"kg","allergens":["GLU"]},
  {"id":"prod_0138","name":"Salchichas frescas de cerdo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0139","name":"Salchichas frescas de pollo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0140","name":"Longaniza fresca","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0141","name":"Butifarra blanca","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0142","name":"Butifarra negra","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0143","name":"Chistorra fresca","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0144","name":"Ternera para hamburguesa gourmet","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0145","name":"Cerdo para hamburguesa","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0146","name":"Mezcla ternera-cerdo para hamburguesa","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0147","name":"Pechuga de pato ahumada","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0148","name":"Lomo de cerdo ahumado","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0149","name":"Costilla de cerdo ahumada","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0150","name":"Ternera deshidratada (jerky)","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0151","name":"Cecina de buey","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0152","name":"Jamón crudo para cocinar","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0153","name":"Tocino en cubos para cocinar","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0154","name":"Panceta en tiras para wok","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0155","name":"Pollo troceado para guiso","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0156","name":"Pavo troceado para estofado","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0157","name":"Conejo en cuartos","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0158","name":"Cerdo para paella","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0159","name":"Ternera para albóndigas finas","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0160","name":"Hamburguesas de pollo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0161","name":"Hamburguesas de pavo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0162","name":"Albóndigas de pollo con huevo","category":"carnes","unit":"kg","allergens":["HUE"]},
  {"id":"prod_0163","name":"Carne de búfalo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0164","name":"Carne de avestruz","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0165","name":"Carne de canguro","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0166","name":"Pato en conserva al natural","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0167","name":"Foie en terrina","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0168","name":"Pulpa de cordero deshuesada","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0169","name":"Churrasco de cordero","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0170","name":"Falda de cordero","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0171","name":"Rabo de cordero","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0172","name":"Carrilleras de cerdo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0173","name":"Papada de cerdo","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0174","name":"Ternera para pinchos morunos","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0175","name":"Cerdo para pinchos morunos","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0176","name":"Pollo para pinchos","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0177","name":"Mezcla de carnes para brochetas","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0178","name":"Carne de ternera para tartar","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0179","name":"Carne de buey para tartar","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0180","name":"Hígado de pato para patés","category":"carnes","unit":"kg","allergens":[]},
  {"id":"prod_0181","name":"Salmón fresco en filetes sin espinas","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0182","name":"Salmón entero limpio","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0183","name":"Salmón ahumado natural","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0184","name":"Merluza fresca entera limpia","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0185","name":"Merluza en filetes sin piel","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0186","name":"Merluza congelada en filetes","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0187","name":"Dorada fresca entera","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0188","name":"Dorada limpiada y escamada","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0189","name":"Lubina fresca entera","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0190","name":"Lubina limpiada y escamada","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0191","name":"Atún fresco en lomos","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0192","name":"Atún congelado para tartar","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0193","name":"Bacalao fresco en lomos","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0194","name":"Bacalao congelado desalado","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0195","name":"Rape fresco en rodajas","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0196","name":"Rape entero limpio","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0197","name":"Rodaballo fresco entero","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0198","name":"Rodaballo en filetes con piel","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0199","name":"Lenguado fresco entero","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0200","name":"Lenguado en filetes sin espinas","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0201","name":"Trucha fresca entera","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0202","name":"Trucha limpia y sin vísceras","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0203","name":"Sardinas frescas enteras","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0204","name":"Sardinas limpias y abiertas","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0205","name":"Boquerones frescos","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0206","name":"Anchoas en salazón","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0207","name":"Caballa fresca entera","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0208","name":"Palometa fresca","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0209","name":"Emperador en lomos","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0210","name":"Pez espada en rodajas","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0211","name":"Besugo fresco entero","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0212","name":"Besugo limpio y escamado","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0213","name":"Mero fresco en trozos","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0214","name":"Corvina fresca entera","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0215","name":"Gallego fresco","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0216","name":"Chernia fresca","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0217","name":"Abadejo fresco","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0218","name":"Fletán fresco en filetes","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0219","name":"Lubina de acuicultura","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0220","name":"Dorada de acuicultura","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0221","name":"Trucha arcoíris de piscifactoría","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0222","name":"Salmón de Noruega entero","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0223","name":"Salmón salvaje del Pacífico","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0224","name":"Merluza del Cantábrico","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0225","name":"Merluza de Nueva Zelanda","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0226","name":"Bacalao del Atlántico","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0227","name":"Pescadilla fresca entera","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0228","name":"Pescadilla en filetes","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0229","name":"Calamar gigante entero","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0230","name":"Calamar limpio congelado","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0231","name":"Chipirones frescos enteros","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0232","name":"Sepia fresca entera","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0233","name":"Sepia limpia y congelada","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0234","name":"Pulpo fresco entero","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0235","name":"Pulpo cocido y congelado","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0236","name":"Langosta azul viva","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0237","name":"Bogavante europeo vivo","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0238","name":"Cigala fresca","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0239","name":"Gamba blanca fresca","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0240","name":"Gamba roja de Huelva","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0241","name":"Langostino crudo pelado","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0242","name":"Langostino cocido congelado","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0243","name":"Nécora fresca","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0244","name":"Centollo fresco","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0245","name":"Percebes frescos","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0246","name":"Navajas frescas","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0247","name":"Berberechos frescos","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0248","name":"Almejas finas","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0249","name":"Almejas japonesas","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0250","name":"Mejillones frescos en red","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0251","name":"Mejillones al vapor en bandeja","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0252","name":"Ostras frescas","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0253","name":"Vieiras frescas con coral","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0254","name":"Zamburiñas","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0255","name":"Caracoles de mar (bucardos)","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0256","name":"Erizos de mar","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0257","name":"Anguila fresca entera","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0258","name":"Congrio fresco entero","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0259","name":"Morena fresca","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0260","name":"Raya fresca en trozos","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0261","name":"Tiburón cazón","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0262","name":"Pejerey fresco","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0263","name":"Jurel fresco entero","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0264","name":"Chicharro fresco","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0265","name":"Bonito del norte en lomos","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0266","name":"Atún rojo en tataki","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0267","name":"Salmón noruego ahumado en lonchas","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0268","name":"Bacalao ahumado","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0269","name":"Filetes de pescado blanco surtido congelado","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0270","name":"Mezcla de pescado azul congelado","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0271","name":"Salmón orgánico certificado","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0272","name":"Dorada ecológica","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0273","name":"Lubina ecológica","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0274","name":"Trucha ecológica","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0275","name":"Merluza MSC certificada","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0276","name":"Bacalao MSC certificado","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0277","name":"Salmón con certificación ASC","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0278","name":"Filetes de rape sin espinas","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0279","name":"Lenguado congelado en filetes","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0280","name":"Rodaballo congelado entero","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0281","name":"Esturión fresco entero","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0282","name":"Salmón del Danubio","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0283","name":"Lucio fresco entero","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0284","name":"Barbo fresco","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0285","name":"Carpa fresca entera","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0286","name":"Tench (tenca) fresca","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0287","name":"Blanco de río (siluro)","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0288","name":"Mújol fresco entero","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0289","name":"Salema fresca","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0290","name":"Breca fresca","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0291","name":"Salmonete de roca fresco","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0292","name":"Salmonete de fango","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0293","name":"Gallineta fresca","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0294","name":"Rape de profundidad","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0295","name":"Abadejo ahumado","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0296","name":"Salmón marinado (gravlax)","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0297","name":"Atún en aceite de oliva (conserva gourmet)","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0298","name":"Boquerones en vinagre","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0299","name":"Anchoas del Cantábrico en aceite","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0300","name":"Caviar de esturión (referencia)","category":"pescados","unit":"g","allergens":["PES"]},
  {"id":"prod_0301","name":"Huevas de lumpo","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0302","name":"Huevas de salmón (ikura)","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0303","name":"Filetes de bacalao sin sal (desalado listo)","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0304","name":"Merluza en tacos para guiso","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0305","name":"Salmón en dados para wok","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0306","name":"Pescado blanco surtido para caldero","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0307","name":"Pescado azul surtido para escabeche","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0308","name":"Lubina en porciones individuales","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0309","name":"Dorada en porciones individuales","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0310","name":"Trucha rellena (base sin relleno)","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0311","name":"Salmón relleno de espinacas (base)","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0312","name":"Filetes de pescado empanados (sin freír)","category":"pescados","unit":"kg","allergens":["PES","GLU","HUE"]},
  {"id":"prod_0313","name":"Pescado al horno listo (sin cocer)","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0314","name":"Mezcla de pescado para sushi (salmón, atún, lubina)","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0315","name":"Pulpa de cangrejo real","category":"pescados","unit":"kg","allergens":["PES","CRU"]},
  {"id":"prod_0316","name":"Cola de rape congelada","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0317","name":"Cabeza de rape para caldo","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0318","name":"Espina de salmón para caldo","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0319","name":"Huesos de pescado blanco para fumet","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0320","name":"Salmón con piel para confitar","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0321","name":"Lubina con piel para a la sal","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0322","name":"Dorada con piel para plancha","category":"pescados","unit":"unidad","allergens":["PES"]},
  {"id":"prod_0323","name":"Trucha ahumada","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0324","name":"Anguila ahumada","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0325","name":"Congrio ahumado","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0326","name":"Filetes de pescado ecológico surtido","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0327","name":"Salmón salvaje con certificación MSC","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0328","name":"Merluza de pincho","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0329","name":"Pescado azul limpio para escabeche","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0330","name":"Sardinas en escabeche listas","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0331","name":"Boquerones fritos congelados","category":"pescados","unit":"kg","allergens":["PES","GLU"]},
  {"id":"prod_0332","name":"Calamares rebozados congelados","category":"pescados","unit":"kg","allergens":["PES","GLU"]},
  {"id":"prod_0333","name":"Filetes de merluza rebozados","category":"pescados","unit":"kg","allergens":["PES","GLU"]},
  {"id":"prod_0334","name":"Pescado blanco en tiras para tempura","category":"pescados","unit":"kg","allergens":["PES","GLU"]},
  {"id":"prod_0335","name":"Salmón en porciones para tartar","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0336","name":"Atún en porciones para ceviche","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0337","name":"Lubina en dados para ceviche","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0338","name":"Pescado blanco ahumado en láminas","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0339","name":"Filetes de pescado sin piel ni espinas (ultrapremium)","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0340","name":"Mezcla de pescado para sopa de pescado","category":"pescados","unit":"kg","allergens":["PES"]},
  {"id":"prod_0341","name":"Langostinos crudos pelados","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0342","name":"Langostinos crudos con cáscara","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0343","name":"Langostinos cocidos pelados","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0344","name":"Langostinos cocidos con cáscara","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0345","name":"Gambas blancas crudas peladas","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0346","name":"Gambas blancas crudas con cáscara","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0347","name":"Gambas rojas de Huelva crudas","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0348","name":"Gambas rojas cocidas","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0349","name":"Cigalas crudas enteras","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0350","name":"Cigalas cocidas enteras","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0351","name":"Bogavante europeo vivo","category":"mariscos","unit":"unidad","allergens":["CRU"]},
  {"id":"prod_0352","name":"Bogavante cocido entero","category":"mariscos","unit":"unidad","allergens":["CRU"]},
  {"id":"prod_0353","name":"Bogavante en trozos crudo","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0354","name":"Langosta azul viva","category":"mariscos","unit":"unidad","allergens":["CRU"]},
  {"id":"prod_0355","name":"Langosta cocida","category":"mariscos","unit":"unidad","allergens":["CRU"]},
  {"id":"prod_0356","name":"Nécoras vivas","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0357","name":"Nécoras cocidas","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0358","name":"Centollos vivos","category":"mariscos","unit":"unidad","allergens":["CRU"]},
  {"id":"prod_0359","name":"Centollos cocidos","category":"mariscos","unit":"unidad","allergens":["CRU"]},
  {"id":"prod_0360","name":"Buey de mar entero","category":"mariscos","unit":"unidad","allergens":["CRU"]},
  {"id":"prod_0361","name":"Cangrejo real (king crab) en pinzas","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0362","name":"Cangrejo de río fresco","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0363","name":"Carabineros crudos","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0364","name":"Carabineros cocidos","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0365","name":"Gamba coral cruda","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0366","name":"Gamba coral cocida","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0367","name":"Langostino tigre crudo","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0368","name":"Langostino tigre cocido","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0369","name":"Mejillones frescos en red","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0370","name":"Mejillones al vapor en bandeja","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0371","name":"Mejillones en escabeche","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0372","name":"Almejas finas frescas","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0373","name":"Almejas japonesas (verdinas)","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0374","name":"Almejas babosas","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0375","name":"Berberechos frescos","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0376","name":"Navajas frescas","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0377","name":"Navajas al natural en lata","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0378","name":"Ostras frescas","category":"mariscos","unit":"unidad","allergens":["MOL"]},
  {"id":"prod_0379","name":"Ostras ahumadas","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0380","name":"Vieiras frescas con coral","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0381","name":"Vieiras sin coral (sólo músculo)","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0382","name":"Zamburiñas frescas","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0383","name":"Percebes frescos","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0384","name":"Erizos de mar frescos","category":"mariscos","unit":"unidad","allergens":["MOL"]},
  {"id":"prod_0385","name":"Pulpo fresco entero","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0386","name":"Pulpo cocido y congelado","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0387","name":"Pulpo tierno en rodajas","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0388","name":"Sepia fresca entera","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0389","name":"Sepia limpia congelada","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0390","name":"Calamar gigante entero","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0391","name":"Calamar limpio congelado","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0392","name":"Chipirones frescos enteros","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0393","name":"Chipirones limpios congelados","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0394","name":"Potón (calamar gigante) en anillas","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0395","name":"Tinta de calamar natural","category":"mariscos","unit":"L","allergens":["MOL"]},
  {"id":"prod_0396","name":"Caracoles de mar (bucardos)","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0397","name":"Cigalas congeladas crudas","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0398","name":"Gambas congeladas crudas peladas","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0399","name":"Langostinos congelados crudos con cáscara","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0400","name":"Mejillones congelados al vapor","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0401","name":"Almejas congeladas","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0402","name":"Berberechos congelados","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0403","name":"Pulpo congelado entero","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0404","name":"Sepia congelada entera","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0405","name":"Calamares congelados limpios","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0406","name":"Mezcla de marisco congelado (gambas, calamar, mejillón)","category":"mariscos","unit":"kg","allergens":["CRU","MOL"]},
  {"id":"prod_0407","name":"Marisco surtido fresco (gamba, nécora, mejillón, almeja)","category":"mariscos","unit":"kg","allergens":["CRU","MOL"]},
  {"id":"prod_0408","name":"Colas de langostino IQF","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0409","name":"Cuerpos de calamar IQF","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0410","name":"Mejillones al natural en lata","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0411","name":"Almejas al natural en lata","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0412","name":"Pulpo al natural en lata","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0413","name":"Gambas al ajillo en conserva","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0414","name":"Mejillones en escabeche en lata","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0415","name":"Carne de centollo en conserva","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0416","name":"Carne de buey de mar en conserva","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0417","name":"Sopa de marisco base (concentrado)","category":"mariscos","unit":"kg","allergens":["CRU","MOL"]},
  {"id":"prod_0418","name":"Fumet de pescado y marisco","category":"mariscos","unit":"L","allergens":["PES","CRU","MOL"]},
  {"id":"prod_0419","name":"Gambas ecológicas certificadas","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0420","name":"Mejillones ecológicos de batea","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0421","name":"Almejas silvestres de ría","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0422","name":"Percebes de Galicia","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0423","name":"Langostinos de Sanlúcar","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0424","name":"Bogavante de Bretaña","category":"mariscos","unit":"unidad","allergens":["CRU"]},
  {"id":"prod_0425","name":"Centollo de Cornisa Cantábrica","category":"mariscos","unit":"unidad","allergens":["CRU"]},
  {"id":"prod_0426","name":"Pulpo de Galicia (certificado)","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0427","name":"Vieiras de Eríndale","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0428","name":"Ostras de Arcade","category":"mariscos","unit":"unidad","allergens":["MOL"]},
  {"id":"prod_0429","name":"Mejillones de la ría de Arosa","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0430","name":"Almejas de Carril","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0431","name":"Gambas de Palamós","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0432","name":"Langosta de las Azores","category":"mariscos","unit":"unidad","allergens":["CRU"]},
  {"id":"prod_0433","name":"Nécoras de Asturias","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0434","name":"Chipirones del Cantábrico","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0435","name":"Sepia del Mediterráneo","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0436","name":"Calamar de potera","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0437","name":"Carne de bogavante en conserva","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0438","name":"Cola de langosta congelada","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0439","name":"Pinzas de cangrejo real cocidas","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0440","name":"Mezcla de marisco para arroz (gamba, calamar, mejillón)","category":"mariscos","unit":"kg","allergens":["CRU","MOL"]},
  {"id":"prod_0441","name":"Cigalas de Rosas","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0442","name":"Gamba blanca del Golfo de Cádiz","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0443","name":"Langostino de Vigo","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0444","name":"Bogavante de Cornisa","category":"mariscos","unit":"unidad","allergens":["CRU"]},
  {"id":"prod_0445","name":"Centollo de Ría","category":"mariscos","unit":"unidad","allergens":["CRU"]},
  {"id":"prod_0446","name":"Nécora de Ría","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0447","name":"Carne de nécora en conserva","category":"mariscos","unit":"kg","allergens":["CRU"]},
  {"id":"prod_0448","name":"Mejillón de Galicia con DOP","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0449","name":"Almeja fina de Carril con IGP","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0450","name":"Berberecho de Ría","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0451","name":"Navaja de Ría","category":"mariscos","unit":"kg","allergens":["MOL"]},
  {"id":"prod_0452","name":"Ostra plana de Belon","category":"mariscos","unit":"unidad","allergens":["MOL"]},
  {"id":"prod_0453","name":"Vieira de peñas", "category": "mariscos", "unit": "kg", "allergens": ["MOL"]}
];
